const CATEGORY_GUIDE = [
  { zh: '浅色 · 沉静', en: 'light-calm' },
  { zh: '深色 · 沉稳', en: 'dark-steady' },
  { zh: '大胆 · 宣言', en: 'bold-statement' },
  { zh: '自然 · 有机', en: 'natural-organic' },
  { zh: '活力 · 创意', en: 'vibrant-creative' },
  { zh: '自定义', en: 'custom' }
]

export const buildStyleImportPrompt = (virtualPath: string): string => {
  const categoryTable = CATEGORY_GUIDE.map((item) => `- ${item.zh} => ${item.en}`).join('\n')
  return [
    '你是一个 PPT 风格解析专家。用户会提供一段描述 PPT 风格的文本（可能是 Markdown、纯文本、HTML 片段、或其他工具的风格描述）。',
    '你必须先使用 read_file 读取文件，再进行解析。',
    '请将其解析为严格 JSON，且只返回 JSON，不要返回额外说明。',
    '',
    '输出结构：',
    '{',
    '  "label": "风格显示名，如 暗夜科技",',
    '  "description": "一句话描述风格特征，20 字以内",',
    '  "category": "分类标签（必须从给定中文枚举中选一个）",',
    '  "aliases": ["搜索别名1", "别名2"],',
    '  "styleSkill": "完整的 Markdown 风格技能文本"',
    '}',
    '',
    'category 映射：',
    categoryTable,
    '',
    'styleSkill 模板要求：',
    '## 主题色',
    '- 主题色：标题 <hex> / 正文 <hex> / 强调 <hex>, <hex>',
    '- 背景：<CSS gradient 或 纯色>',
    '- 卡片：<rgba>，边框 <color>',
    '',
    '# <label>',
    '',
    '**分类**: <category 英文标识>',
    '',
    '## 视觉特征',
    '- <提取的视觉特征要点>',
    '',
    '## 适用场景',
    '<提取的适用场景>',
    '',
    '## 布局建议',
    '- 保持风格一致性',
    '- 使用主题色系统定义的颜色',
    '- 注意文字层级和留白',
    '',
    '## 动画建议',
    '`<动画名称>` / `<动画名称>` / `<动画名称>`',
    '',
    '## 字体建议',
    '<字体推荐>',
    '',
    '## 不要做',
    '<该风格应避免的设计元素>',
    '',
    '规则：',
    '1. 如果用户文本中有明确颜色值，优先使用。',
    '2. 如果字段缺失，根据风格语义补充合理默认值。',
    '3. category 字段必须输出中文枚举值；styleSkill 中的分类必须输出对应英文标识。',
    '4. 只输出 JSON，且使用 ```json ... ``` 包裹。',
    '5. 如果文件较长，分段多次 read_file 后再总结，不要只读取开头。',
    '',
    `读取文件路径：${virtualPath}`
  ].join('\n')
}
